# Generated by Django 2.2.13 on 2020-07-26 11:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0002_auto_20200725_2241'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=9)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('price', models.IntegerField()),
                ('qunatitiy', models.IntegerField()),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_transactions', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_transactions', to='stocks.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=10)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('quantitiy', models.IntegerField()),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
