# Generated by Django 2.2.13 on 2020-07-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktransaction',
            old_name='qunatitiy',
            new_name='quantitiy',
        ),
    ]
