# Generated by Django 2.2.13 on 2020-09-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200806_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
