# Generated by Django 2.2.13 on 2020-07-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200726_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneytransaction',
            old_name='quantitiy',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='stocktransaction',
            old_name='quantitiy',
            new_name='quantity',
        ),
    ]
