# Generated by Django 2.2.13 on 2020-09-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20200807_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='주식 코드'),
        ),
    ]
